# .github/workflows/deploy.yml
name: Build + CLI Deploy to EdgeOne Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout repository & submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - name: Install & Build
        run: |
          pnpm install --frozen-lockfile
          pnpm build

      # ✅ 安装 Edgeone CLI（全局）
      - name: Install Edgeone CLI
        run: npm install -g edgeone

      # ✅ 使用 CLI 部署
      - name: Deploy to EdgeOne Pages
        run: |
          edgeone pages deploy ./dist \
            -n baili-blog \
            -t ${{ secrets.EDGEONE_API_TOKEN }} \
            -e production
