# .github/workflows/deploy.yml
name: Build + CLI Deploy to EdgeOne Pages

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'

      - run: pnpm install --frozen-lockfile
      - run: pnpm build

      - name: Deploy to EdgeOne Pages
        run: |
          npx @tencent/edgeone-cli pages deploy ./dist \
            -n baili-blog \
            -t ${{ secrets.EDGEONE_API_TOKEN }} \
            -e prod
